title: example explicit solvent ddmd run # title 
continue: False # Whether to start fresh or restart a simulation 
conda_env: /homes/heng.ma/miniconda3/envs/ddmd # conda env to run simulation
n_sims: 6 # number of simulations 
output_dir: /scratch/heng/ddmd/bba_test # directory to deposit output files

md_setup: 
  pdb_file:  # input pdb file 
  top_file:  # MD topology file
  checkpoint: null # MD checkpoint t oresetart simulation 
  gpu_id: 0 # no need to changed for single GPU MDs, cuda devices defined from run command
  # output_traj: output.dcd # no need to change these two 
  # output_log: output.log
  sim_time: 10 # length of each segment simulation in ns 
  report_time: 10 # how often a frame is written in ps
  dt: 2 # MD time step in fs
  explicit_sol: True # whether the system is using explicit solvent model
  temperature: 300 # in K
  pressure: 1. # in bar 
  nonbonded_cutoff: 1 # in nm 
  init_vel: False # whether to initialize atom velocity
  max_iter: 1000000 # Maximum iterations of MD simulations, default at large number to keep MD running 

ml_setup: 
  n_train_start: 1000 # number of simulation frames to start training 
  retrain_freq: 1.5 # retrain the simulation once current n_frames is 1.5X higher
  batch_size: 256 # training batch size 
  epochs: 10 # traning epochs
  latent_dim: 3 # latent dimension 
  n_conv_layers: 4 # number of conv layers
  feature_maps: [16, 16, 16, 16] # depth of each conv layer
  filter_shapes: [[3, 3], [3, 3], [3, 3], [3, 3]] # size of filter for conv layers 
  strides: [[1, 1], [1, 1], [1, 1], [2, 2]] # strides of conv layers 
  dense_layers: 1 # number of dense layers
  dense_neurons: [128] # number of neurons for dense layers 
  dense_dropouts: [0.5] # dropout rate of dense layers 
  atom_sel: name CA # atom selection string for contact map
  cutoff: 8 # cutoff distance for contact map in angstrom

infer_setup: 
  n_outliers: 50 # number of outliers to identify
  md_threshold: 0.75 # a simulation is qualified to be stop, if it finishes 0.75 of the run and still renders no outliers 
  screen_iter: 10 # output outlier list every 10 iteration
  # uncomment if needed 
  # ref_pdb: /homes/heng.ma/Research/ddmd/ddmd/data/pdbs/bba/1FME-folded.pdb # reference pdb for rmsd against target state 
  # atom_sel: name CA # selection string for rmsd calculation
  n_neighbors: 20 # number of neighbors to calculate LOF

