title: RNA folding ddmd run
continue: False
conda_env: /project/zerze/ddmd
n_sims: 6
output_dir: ./test_RMSDnudge_tohigh

md_setup:
  pdb_file: /project/zerze/ayushg/argonne/configs/ICs/Q_0.503158.gro
  top_file: /project/zerze/ayushg/argonne/configs/configs_u/topol.top
  sim_time: 10 # in ns
  report_time: 10 # in ps
  dt: 2 # in fs
  explicit_sol: True
  temperature: 300 # in K
  pressure: 1. # in bar
  nonbonded_cutoff: 1. # in nm
  init_vel: False # whether to initialize atom velocity
  max_iter: 1000000 # Maximum iterations of MD simulation sections, default at large number to keep MD running

ml_setup:
  n_train_start: 1000 # number of simulation frames to start training
  retrain_freq: 2000 # retrain the simulation once current n_frames is 2000 more than before OR 1.5X higher
  batch_size: 256 # training batch size
  epochs: 10 # training epochs
  latent_dim: 6 # latent dimension
  n_conv_layers: 4 # number of conv layers
  feature_maps: [32, 32, 32, 32] # depth of each conv layer
  filter_shapes: [[3, 3], [3, 3], [3, 3], [3, 3]] # size of filter for conv layers
  strides: [[1, 1], [1, 1], [1, 1], [1,1]] # strides of conv layers
  dense_layers: 1 # number of dense layers
  dense_neurons: [128] # number of neurons for dense layers
  dense_dropouts: [0.5] # dropout rate of dense layers
  atom_sel: name C1' or name C3' # atom selection string for contact map
  cutoff: 7 # cutoff distance for contact map in angstrom

infer_setup:
  n_outliers: 50 # number of outliers to identify
  md_threshold: 0.75 # a simulation is qualified to be stop, if it finishes 0.75 of the run and still renders no outliers
  screen_iter: 10 # output outlier list every 10 iteration
  n_neighbors: 20 # number of neighbors to calculate LOF
  ref_pdb: /project/zerze/ayushg/argonne/folded_reference.gro
  atom_sel: resid 1:10 and not name H*
  nudge: high

